server:
  port: 8081
  
spring:
  profiles: default
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    url: jdbc:mysql://104.154.156.17:3306/my-database
#    username: my-user
#    password: my-password
#    driverClassName: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://${_DATASOURCE_ADDRESS:104.154.156.17:3306}/${_DATASOURCE_TABLESPACE:my-database}
#    username: ${_DATASOURCE_USERNAME:my-user}
#    password: ${_DATASOURCE_PASSWORD:my-password}
#    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: product
          destination: shop
          contentType: application/json
        output:
          destination: shop
          contentType: application/json
          
---
spring:
  profiles: test
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${spring.embedded.kafka.brokers}
      bindings:
        input:
          group: product
          destination: test
          contentType: application/json
        output:
          destination: test
          contentType: application/json
    
    

    